### ISSUE TITLE
License incompatibility

### ISSUE THREAD

**Issue by brunchboy** [overtone/ableton-link#4]
I just realized that even if you do resolve #3 I can’t embed this in Beat Link Trigger, because Ableton Link can’t be released with a permissive license like I use. But it also cannot be released with the MIT license as you are doing; please see Ableton’s [License](https://github.com/Ableton/link/blob/master/LICENSE.md). They chose the GPL, which is a very restrictive license. You will need to change your project to use that license as well, and so will your users.

**Comment by brunchboy** [comment]
If you want to be able to use Link from within projects like Overtone with permissive licenses like the MIT license, I suggest you simply use my [Carabiner](https://github.com/brunchboy/carabiner#carabiner) project, and communicate with it as a separate process over the network the way I do with Beat Link Trigger. This socket-level separation avoids license entanglement with the GPL. You can find my Clojure code for talking to Carabiner here: https://github.com/brunchboy/beat-link-trigger/blob/master/src/beat_link_trigger/carabiner.clj

**Comment by hlolli** [comment]
I wouldn't have guessed that Ableton a capitalist corporation would ever release something under GPL, I'm impressed. Didn't pay much attention to the licenceing, the Clojure code and the c++ bindings aren't required to use GPL, but distributeing the binaries it's a must I realize. So I will change. I actually don't know why Overtone itself was licenced MIT in the first place, since Supercollider is licenced GPL too. So with same argument, the licenceing of Overtone is also incompatable. I will change the licence on ableton-link and discuss about relicenceing Overtone itself with Sam Aaron.

**Comment by hlolli** [comment]
Now licenced under GPL3+ 
https://github.com/overtone/ableton-link/commit/208e4a81411162e21b86627478292b1668524eff

ps. oops, did hashtag 370 on the commit messge instead of 4.
